### ISSUE TITLE
Support for onFocus and onBlur event

### ISSUE THREAD

**Issue by wagabundy** [IvanIhnatsiuk/react-native-advanced-input-mask#29]
I'm looking for a component to replace **react-native-text-input-mask** which doesn't work in RN 0.76. Your solution is almost perfect. Unfortunately, support for *onFocus* and *onBlur* events is missing.

Do you plan to add such an addition in the near future? If not, could you suggest how to implement it based on your code

**Comment by wagabundy** [comment]
It seems to me that it is not possible to attach handlers handling the onBlur and onFocus events to the control, similarly to the way it is possible for the native InputText with react-native.
This functionality is necessary in my case.

**Comment by IvanIhnatsiuk** [comment]
Sounds strange, in my test application in example I subscribe to these events and everything works fine, can you tell me what version of the library you are using and test this with the latest version of the package?


https://github.com/user-attachments/assets/f9134c4c-25d5-49fd-9a81-5487e95a8e36

**Comment by wagabundy** [comment]
Sorry. My mistake. Everything works fine.
